language: ko-KR

reviews:
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_in_walkthrough: false
  
  sequence_diagrams: true
  related_issues: true
  related_prs: true
  suggested_reviewers: false
  poem: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    base_branches:
      - "master"
      - "develop"

chat:
  auto_reply: true
