package com.umc.domain.model.enums

enum class PointType {
    BEST_WORKBOOK,
    WARNING,
    OUT,
    CUSTOM,
    BLOG_CHALLENGE,
    BEST_WORKBOOK_V2,
    UMC_EVENT_REVIEW,
    PEER_REVIEW_SUBMISSION,
    NO_WORKBOOK_MISSION,
    STUDY_LATE,
    STUDY_ABSENT,
    EVENT_LATE,
    EVENT_EARLY_LEAVE,
    EVENT_LATE_CANCEL,
    EVENT_NO_SHOW,
    PART_LEAD_FEEDBACK_LATE,
    SCHOOL_CORE_MEETING_ABSENT,
    SCHOOL_CORE_TASK_NOT_COMPLETED
}