package com.umc.domain.model.enums

enum class RoleType {
    SUPER_ADMIN,
    CENTRAL_PRESIDENT,
    CENTRAL_VICE_PRESIDENT,
    CENTRAL_OPERATING_TEAM_MEMBER,
    CENTRAL_EDUCATION_TEAM_MEMBER,
    CHAPTER_PRESIDENT,
    SCHOOL_PRESIDENT,
    SCHOOL_VICE_PRESIDENT,
    SCHOOL_PART_LEADER,
    SCHOOL_ETC_ADMIN
}